### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SummaryCards#12]
## Tasks

- [ ] Update release notes
- [ ] Update README.md
- [ ] Update version number
- [ ] Create tag
- [ ] Update `semantic-mediawiki.org`
  - [ ] Run `composer update`
  - [ ] Check [Special:Version](https://www.semantic-mediawiki.org/wiki/Special:Version)
- [ ] Announce via mail
- [ ] Do a release tweet on Twitter

@mwjames I guess it is time

**Comment by kghbln** [comment]
Closed per https://github.com/SemanticMediaWiki/SummaryCards/issues/17
